/* A packrat parser generated by PackCC 1.8.0 */

#ifndef PCC_INCLUDED_PARSER_H
#define PCC_INCLUDED_PARSER_H

#include "ast.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct mmz_context_tag mmz_context_t;

mmz_context_t *mmz_create(parser_state_t *auxil);
int mmz_parse(mmz_context_t *ctx, ast_node_t **ret);
void mmz_destroy(mmz_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_PARSER_H */
