version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'mmz'
      POSTGRES_USER: 'mmz'
      POSTGRES_DB: 'sqlillo'
    networks:
      - common

  server:
    build: 
      dockerfile: Dockerfile
      context: ./api/
    restart: always
    ports: 
      - "8000:8000"
    environment:
      PORT: "8000"
      DATABASE_URL: 'postgresql://mmz:mmz@db:5432/sqlillo?sslmode=disable'
    networks:
      - common

networks:
  common: {}
