---
git-base: &git-base
  type: git
  icon: git
  check_every: "10s"
  source:
    uri: https://oauth2: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@github.com/MarceColl/sqlillo-royale.git

resource_types:
  - name: nomad
    type: registry-image
    source:
      repository: registry.digitalocean.com/dziban/concourse-nomad-resource
      tag: latest
      username: dop_v1_f52f933c8c9724ea38c6505bddc0c8245a0ba4eb0b3c9ff2891f4e432c179ef9
      password: dop_v1_f52f933c8c9724ea38c6505bddc0c8245a0ba4eb0b3c9ff2891f4e432c179ef9

resources:
- name: runner-src
  type: git
  icon: git
  check_every: "10s"
  source:
    uri: https://oauth2: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@github.com/MarceColl/sqlillo-royale.git
    paths:
      - "mmz/*"
- name: server-src
  type: git
  icon: git
  check_every: "10s"
  source:
    uri: https://oauth2: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@github.com/MarceColl/sqlillo-royale.git
    paths:
      - "sqlillo/*"
      - "canvas-renderer/*"
- name: infra-src
  type: git
  icon: git
  check_every: "10s"
  source:
    uri: https://oauth2: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@github.com/MarceColl/sqlillo-royale.git
    paths:
      - "infra/*"
- name: server-image
  type: registry-image
  icon: docker
  source:
    repository: registry.digitalocean.com/dziban/sqlillo-server
    tag: latest
    username: dop_v1_f52f933c8c9724ea38c6505bddc0c8245a0ba4eb0b3c9ff2891f4e432c179ef9
    password: dop_v1_f52f933c8c9724ea38c6505bddc0c8245a0ba4eb0b3c9ff2891f4e432c179ef9
- name: runner-image
  type: registry-image
  icon: docker
  source:
    repository: registry.digitalocean.com/dziban/sqlillo-runner
    tag: latest
    username: dop_v1_f52f933c8c9724ea38c6505bddc0c8245a0ba4eb0b3c9ff2891f4e432c179ef9
    password: dop_v1_f52f933c8c9724ea38c6505bddc0c8245a0ba4eb0b3c9ff2891f4e432c179ef9
- name: runner-deploy
  type: nomad
  icon: server
  source:
    url: http://100.98.149.54:4646
    name: runner
- name: server-deploy
  type: nomad
  icon: server
  source:
    url: http://100.98.149.54:4646
    name: sqlillo-royale

jobs:
- name: build-server
  plan:
  - get: server-src
    trigger: true
  - task: build-server
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: server-src
        path: .
      params:
        CONTEXT: sqlillo
      outputs:
      - name: image
      caches:
      - path: cache
      run:
        path: build
  - put: server-image
    params: {image: image/image.tar}

- name: build-runner
  plan:
  - get: runner-src
    params:
      version: latest
    trigger: true
  - task: build-server
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: runner-src
        path: .
      params:
        CONTEXT: mmz
      outputs:
      - name: image
      caches:
      - path: cache
      run:
        path: build

  - put: runner-image
    params: {image: image/image.tar}

- name: deploy-runner
  plan:
  - get: infra-src
    trigger: true
  - get: runner-image
    trigger: true

  - put: runner-deploy
    params:
      name: runner
      job_path: infra-src/infra/nomad/runner.nomad

- name: deploy-server
  plan:
  - get: infra-src
    trigger: true
  - get: server-image
    trigger: true

  - put: server-deploy
    params:
      name: sqlillo-royale
      job_path: infra-src/infra/nomad/sqlillo.nomad

