resources:
- name: repo
  type: git
  source:
    uri: https://oauth2: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@github.com/MarceColl/sqlillo-royale.git

jobs:
- name: build-server
  plan:
  - get: repo
    trigger: true
  - task: build-server
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: quay.io/buildah/stable
      inputs:
        - name: repo
      run:
        path: sh
        args:
        - "-cx"
        - |
          pacman -Syu --noconfirm
          pacman -S buildah --noconfirm
          cd repo/server
          ls -l .
          buildah build --isolation=chroot -f Dockerfile -t sqlillo-royale-server:latest .

- name: build-runner
  plan:
  - get: repo
    trigger: true
  - task: build-frontend
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: quay.io/buildah/stable
      run:
        path: sh
        args:
        - "-cx"
        - |
          pacman -Syu --noconfirm
          pacman -S buildah --noconfirm
          ls -l .
